### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kimihiroh**
Add unseen test file in the submission structure format

### CODE REVIEW

**Comment by kimihiroh** [comment]
Could you check the change? Thanks. @lindiatjuatja @neubig

**Review by neubig — CHANGES_REQUESTED** [review]
Can you please add documentation of the expected format of this file?

**Comment by kimihiroh** [comment]
I added a short description of the file. Let me know if I should elaborate more. 
Cc. @lindiatjuatja

**Review by neubig — COMMENTED** [review]
Thank you. Sorry, to clarify, why must the `test_questions.csv` file be submitted? This file is part of the assignment materials and shouldn't be different between the different submissions.

**Comment by kimihiroh** [comment]
Yes, you are right that `test_questions.csv` would not be changed and, technically speaking, does not need to be submitted. I can remove it from the submission structure, if that is better.

The only reason why I have it there is that if we do not have it, students might think that they need to remove it from the repo they submit, considering that the file is in their repo by default like `README.md`.

**Review by neubig — COMMENTED** [review]
Sorry, maybe there's a misunderstanding here. There is no need for students to base their repo on this repo. The README.md in their repo should describe how to run their system, it doesn't need to be the one from this repo.

I would suggest we clarify this on Piazza, but close this PR.

**Comment by kimihiroh** [comment]
Thanks for the clarification!

**Pull request closed without merging**
